[tool.poetry]
name = "helpcenter"
version = "0.1.0"
description = ""
authors = ["Alpha <piotr@piotryordanov.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mkdocs-material = "^9.1.21"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
